dataset_params:
  root_dir: /root/mnt/share/Voxceleb
  frame_shape: [256, 256, 3]
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1


model_params:
  common_params:
    num_kp: 20
    sections:  [[[384, 385, 386, 387, 388, 390, 263, 362, 398, 466, 373, 374, 249, 380, 381, 382, 336, 285, 295, 282, 283, 276, 300, 293, 334, 296], 3], [[160, 33, 161, 163, 133, 7, 173, 144, 145, 246, 153, 154, 155, 157, 158, 159, 70, 46, 53, 52, 65, 55, 107, 66, 105, 63], 3], [[181, 84, 17, 314, 405, 321, 375, 291, 409, 270, 269, 267, 0, 37, 39, 40, 185, 61, 146, 91], 6], [[178, 87, 14, 317, 402, 318, 324, 308, 415, 310, 311, 312, 13, 82, 81, 80, 191, 78, 95, 88], 4], [[356, 454, 323, 361, 288, 397, 172, 58, 132, 93, 234, 127, 162, 21, 54, 103, 67, 109, 10, 338, 297, 332, 284, 251, 389], 4]]
    headmodel_sections:   [[[384, 385, 386, 387, 388, 390, 263, 362, 398, 466, 373, 374, 249, 380, 381, 382], 10], [[336, 285, 295, 282, 283, 276, 300, 293, 334, 296], 10], [[160, 33, 161, 163, 133, 7, 173, 144, 145, 246, 153, 154, 155, 157, 158, 159], 10], [[70, 46, 53, 52, 65, 55, 107, 66, 105, 63], 10], [[181, 84, 17, 314, 405, 321, 375, 291, 409, 270, 269, 267, 0, 37, 39, 40, 185, 61, 146, 91, 178, 87, 14, 317, 402, 318, 324, 308, 415, 310, 311, 312, 13, 82, 81, 80, 191, 78, 95, 88], 20]]
    image_channel: 3                    
    feature_channel: 32
    estimate_jacobian: False   # True
  kp_detector_params:
     temperature: 0.1
     block_expansion: 32            
     max_features: 1024
     scale_factor: 0.25         # 0.25
     num_blocks: 5
     reshape_channel: 16384  # 16384 = 1024 * 16
     reshape_depth: 16
  he_estimator_params:
     block_expansion: 64            
     max_features: 2048
     num_bins: 66
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    reshape_channel: 32
    reshape_depth: 16         # 512 = 32 * 16
    num_resblocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 5
      # reshape_channel: 32
      reshape_depth: 16
      compress: 4
  discriminator_params:
    scales: [1]
    block_expansion: 32                 
    max_features: 512
    num_blocks: 4
    num_channels: 4
    sn: True

train_params:
  sigma_err: 0.001
  pca_update_freq: 100
  num_epochs: 4000
  num_repeats: 1
  epoch_milestones: [180,]
  lr_generator: 2.0e-4
  lr_discriminator: 2.0e-4
  lr_kp_detector: 2.0e-4
  lr_he_estimator: 2.0e-4
  lr_headmodel: 2.0e-4
  gan_mode: 'hinge'    # hinge or ls
  batch_size: 16
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 1
  hopenet_snapshot: 'ckpt/hopenet_robust_alpha1.pkl'
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1                
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 0
    equivariance_jacobian: 0    # 10
    keypoint: 0
    headpose: 0
    expression: 0
    recon: 0
    k_e: 0
    regularizor: 0
    coefs: 0
    coefs_match: 0
    segmentation: 10
    priors: 0
    motion_match: 50
    prior_sparsity: 0

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'
